// Generated by tools/audio/radio_voice.py --write-durations from measured mission-radio WAVs.
// Empty until clips are generated; MissionRadioDirector falls back to its word-count estimate.
// Do not edit by hand — regenerate after any clip generation run.

namespace GunsOnly.Sim;

public static class MissionRadioClipDurations {
    static readonly Dictionary<string, double> Seconds = new() {
        ["approach-recovery-continue"] = 1.179,
        ["control-bingo-rtb"] = 1.342,
        ["control-commit-short"] = 0.872,
        ["control-radar-contact"] = 1.419,
        ["lso-add-power"] = 0.949,
        ["lso-bolter"] = 0.585,
        ["lso-come-left"] = 0.888,
        ["lso-come-right"] = 0.940,
        ["lso-fast"] = 0.724,
        ["lso-high"] = 0.844,
        ["lso-low"] = 0.749,
        ["lso-power"] = 0.549,
        ["lso-waveoff"] = 0.749,
        ["pilot-base"] = 1.494,
        ["pilot-base-touch-and-go"] = 1.955,
        ["pilot-bingo"] = 0.932,
        ["pilot-check-in"] = 1.957,
        ["pilot-commit-ack"] = 0.900,
        ["pilot-crosswind"] = 1.135,
        ["pilot-drone-away"] = 0.751,
        ["pilot-fox-two"] = 0.867,
        ["pilot-going-around"] = 1.241,
        ["pilot-initial"] = 1.138,
        ["pilot-joker"] = 0.942,
        ["pilot-landing-ack"] = 1.113,
        ["pilot-recovery-request"] = 2.157,
        ["pilot-remington"] = 0.738,
        ["pilot-rtb"] = 1.476,
        ["pilot-separating"] = 1.107,
        ["pilot-splash"] = 1.099,
        ["pilot-touch-and-go-ack"] = 2.183,
        ["pilot-winchester"] = 0.752,
        ["tower-bolter"] = 1.179,
        ["tower-break-approved"] = 1.493,
        ["tower-check-gear-downwind"] = 1.481,
        ["tower-cleared-arrested-landing"] = 1.656,
        ["tower-cleared-touch-and-go"] = 1.808,
        ["tower-continue-check-gear"] = 1.621,
        ["tower-going-around-ack"] = 0.845,
        ["tower-hold-position"] = 1.284,
        ["tower-rapier-2-cleared-landing"] = 2.041,
        ["tower-rapier-3-cleared-landing"] = 2.120,
        ["tower-rapier-4-cleared-landing"] = 2.107,
        ["tower-waveoff-gear"] = 2.005,
        ["traffic-rapier-2-base"] = 2.215,
        ["traffic-rapier-2-landing-ack"] = 2.294,
        ["traffic-rapier-3-base"] = 2.268,
        ["traffic-rapier-3-landing-ack"] = 2.264,
        ["traffic-rapier-4-base"] = 2.269,
        ["traffic-rapier-4-landing-ack"] = 2.178,
    };

    /// <summary>Longest measured take for the catalog id, in seconds.</summary>
    public static bool TryGet(string id, out double seconds) =>
        Seconds.TryGetValue(id, out seconds);

    public static int Count => Seconds.Count;
}
