// Generated by tools/audio/radio_voice.py --write-durations from measured mission-radio WAVs.
// Empty until clips are generated; MissionRadioDirector falls back to its word-count estimate.
// Do not edit by hand — regenerate after any clip generation run.

namespace GunsOnly.Sim;

public static class MissionRadioClipDurations {
    static readonly Dictionary<string, double> Seconds = new() {
        ["approach-recovery-continue"] = 2.500,
        ["control-bingo-rtb"] = 1.900,
        ["control-commit"] = 3.900,
        ["control-confirm-safe"] = 3.350,
        ["control-radar-contact"] = 2.750,
        ["launch-cleared"] = 2.200,
        ["lso-add-power"] = 1.150,
        ["lso-bolter"] = 0.850,
        ["lso-come-left"] = 1.700,
        ["lso-come-right"] = 1.050,
        ["lso-fast"] = 1.250,
        ["lso-high"] = 0.850,
        ["lso-low"] = 0.550,
        ["lso-power"] = 0.750,
        ["lso-waveoff"] = 0.950,
        ["pilot-airborne"] = 2.850,
        ["pilot-base"] = 3.200,
        ["pilot-base-gear-unsafe"] = 2.450,
        ["pilot-bingo"] = 2.450,
        ["pilot-check-in"] = 2.500,
        ["pilot-checklist-recovery-config"] = 3.300,
        ["pilot-departure-airborne"] = 2.600,
        ["pilot-downwind"] = 2.950,
        ["pilot-downwind-gear-unsafe"] = 1.650,
        ["pilot-drone-away"] = 1.100,
        ["pilot-fox-two"] = 1.400,
        ["pilot-guns"] = 1.400,
        ["pilot-initial"] = 1.850,
        ["pilot-joker"] = 1.950,
        ["pilot-land"] = 2.800,
        ["pilot-recovery-request"] = 4.500,
        ["pilot-remington"] = 0.750,
        ["pilot-rtb"] = 2.950,
        ["pilot-separating"] = 3.050,
        ["pilot-splash"] = 1.750,
        ["pilot-switch-safe"] = 1.900,
        ["pilot-winchester"] = 1.050,
        ["tower-bolter"] = 1.950,
        ["tower-break-approved"] = 2.750,
        ["tower-check-gear-downwind"] = 2.600,
        ["tower-cleared-arrested-landing"] = 3.900,
        ["tower-continue-check-gear"] = 3.050,
        ["tower-hold-position"] = 2.450,
        ["tower-join-initial"] = 5.100,
        ["tower-waveoff-gear"] = 2.700,
        ["traffic-rapier-2-base"] = 2.800,
        ["traffic-rapier-2-base-alt"] = 3.450,
        ["traffic-rapier-2-final"] = 3.400,
        ["traffic-rapier-2-final-alt"] = 2.600,
        ["traffic-rapier-3-base"] = 3.700,
        ["traffic-rapier-3-base-alt"] = 3.850,
        ["traffic-rapier-3-final"] = 4.400,
        ["traffic-rapier-3-final-alt"] = 2.250,
        ["traffic-rapier-4-base"] = 3.950,
        ["traffic-rapier-4-base-alt"] = 4.400,
        ["traffic-rapier-4-final"] = 4.450,
        ["traffic-rapier-4-final-alt"] = 3.400,
    };

    /// <summary>Longest measured take for the catalog id, in seconds.</summary>
    public static bool TryGet(string id, out double seconds) =>
        Seconds.TryGetValue(id, out seconds);

    public static int Count => Seconds.Count;
}
